import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { APP_VERSION } from './version';

const resources = {
  zh: { translation: {
    brand: { subtitle: '在线账号成活与额度检测', version: `v${APP_VERSION.version}` },
    header: { guide: '操作指引', openSource: '开源声明', privacy: '凭据仅保留在当前进程', desktop: '桌面模式', mobile: '移动端', preview: '浏览器预览', switchLanguage: 'Switch to English' },
    updates: { check: '检查更新', available: '发现更新', eyebrow: 'GitHub Releases', title: '发现新版本 v{{version}}', current: '当前已是最新版本 v{{version}}', failed: '暂时无法检查更新，请稍后重试', later: '稍后再说', download: '前往下载', selectApiKey: '请先导入账号或添加自定义 API 供应商', started: '局域网 API 服务已开启，请保存配对密钥', stopped: '局域网 API 服务已停止', startFailed: '无法启动局域网 API：{{message}}', stopFailed: '无法停止局域网 API 服务', copied: '已复制到剪贴板', copyFailed: '无法复制，请手动复制', titleLan: '局域网 API 服务', subtitle: '将此手机作为已配对电脑的 OpenAI 兼容 API 地址', hint: '仅转发 /v1/models、/v1/chat/completions 与 /v1/responses。服务在前台通知中运行，停止后配对密钥立即失效。', proxyHintTitle: '代理和局域网必须同时可用', proxyHint: '外国模型通常需要手机代理。若开启代理后电脑连不上、关闭后可以，说明当前代理拦截了 LAN；请启用“允许 LAN / 绕过局域网”或更换支持局域网的代理。临时使用时：手机自测开代理，电脑连接关代理。', port: '服务端口', start: '开启 API 服务', stop: '停止 API 服务', running: '运行中', idle: '未开启', pool: '{{count}} 个可用上游', poolReady: '启用自定义供应商时只使用该供应商；关闭后恢复导入账号轮询', poolManage: '点击管理上游 · 已启用 {{enabled}} / {{total}}', poolListTitle: 'LAN 上游', poolActiveCount: '{{enabled}} / {{total}} 已启用', providerUpstream: '自定义 API', toggleUpstream: '切换 {{name}}', poolUpdated: '上游设置已更新，运行中的服务已立即生效', poolUpdateFailed: '上游更新失败，原设置保持不变', poolEmptyStopped: '没有启用的上游，局域网 API 服务已停止', poolEmpty: '请先导入账号或添加自定义 API 供应商', copyAddress: '复制 API 地址', copyToken: '复制配对密钥', tokenUnavailable: '服务在应用外启动；请停止后重新启动，以生成新的配对密钥。', test: '测试连接', retest: '重新测试', testingModels: '正在获取可用模型...', testingModel: '已发现 {{count}} 个模型，正在随机测试 {{model}}...', testPassed: '测试通过 · {{elapsed}} ms', testFailed: '测试失败', testModelDetail: '发现 {{count}} 个模型 · 随机测试 {{model}}', testUpstream: '上游：{{name}} · {{protocol}}', testResponse: '响应：{{response}}', testModels: '可用模型', testNoModels: '未发现可测试的模型', testError: '错误：{{message}}' },
    splash: { subtitle: '账号状态与 Codex 额度检测', loading: '正在启动安全检测环境' },
    metrics: { label: '账号检测统计', rate: '在线成活率', verifiedRatio: '{{alive}} / {{tested}} 已验证', verified: '已验证账号', verifiedHint: '实际请求已返回结果', pending: '待验证', invalid: '凭据失效', limited: '被限流', total: '总账号' },
    operations: { label: '工作区状态', localState: '本地工作区已自动保存', attention: '{{count}} 个账号需要处理', clear: '当前没有待处理异常', running: '正在验证 {{done}} / {{total}}' },
    actions: { importFolder: '导入文件夹', importFiles: '导入文件', pasteJson: '粘贴 JSON', validate: '在线验证', pauseValidation: '暂停验证', resumeValidation: '继续验证', cancelValidation: '取消验证', cancellingValidation: '正在取消', deleteInvalid: '删除失效', exportRemaining: '导出剩余', exportReport: '导出验证报告', clear: '清空', close: '关闭', cancel: '取消', refreshQuota: '刷新额度', previous: '上一步', next: '下一步', finish: '完成', exitGuide: '退出指引', retryIp: '重新检测 IP', startValidation: '开始验证', confirmDelete: '确认删除', parseImport: '解析并导入', understood: '知道了' },
    mobile: { accounts: '账号列表', details: '账号详情', api: '局域网 API' },
    providers: { add: '自定义 API 供应商', list: '自定义 API 供应商', eyebrow: '上游配置', addTitle: '添加 API 供应商', editTitle: '编辑 API 供应商', name: '名称', namePlaceholder: '例如：供应商 3', protocol: '上游协议', model: '配置模型', modelPlaceholder: '输入或获取模型', fetchModels: '获取模型', fetchingModels: '正在获取...', selectModel: '选择模型', modelsFound: '已获取 {{count}} 个模型', noModels: '未获取到可用模型', modelsHint: '从供应商的 /v1/models 获取支持的模型', fetchModelsFirst: '请先填写 Base URL 和 API Key', fetchModelsFailed: '获取模型失败：{{message}}', useInPool: '设为当前唯一 API 供应商', disableActiveFirst: '当前正在使用“{{name}}”，请先关闭它再启用此供应商', enabled: '已启用', disabled: '已停用', edit: '编辑供应商', delete: '删除供应商', save: '保存供应商', saved: 'API 供应商已保存', deleted: 'API 供应商已删除', invalidUrl: '请输入有效的 HTTP 或 HTTPS Base URL', required: '名称、Key 和模型不能为空' },
    search: { placeholder: '搜索邮箱、账号 ID、格式', clear: '清除搜索' },
    filters: { all: '全部', pending: '待验证', alive: '在线正常', invalid: '凭据失效', limited: '被限流', attention: '需处理', count: '{{count}} 个账号' },
    table: { account: '账号', source: '来源', status: '在线状态', quota: 'Codex 额度', checkedAt: '验证时间', details: '详情', noResults: '没有匹配的账号', pagination: '账号分页', pageSummary: '显示 {{start}}-{{end}}，共 {{count}} 条', page: '第 {{page}} / {{total}} 页', previousPage: '上一页', nextPage: '下一页' },
    empty: { title: '等待账号数据', details: '选择账号查看详情' },
    status: { untested: '未验证', unsupported: '待验证', checking: '验证中', alive: '在线正常', unauthorized: '凭据失效', forbidden: '无权限', rate_limited: '被限流', server_error: '服务异常', network_error: '网络失败' },
    formats: { oauth: '通用 OAuth' },
    quota: { fiveHours: '5 小时', weekly: '周额度', days: '{{count}} 天', hours: '{{count}} 小时', minutes: '{{count}} 分钟', short: '短期', long: '长期', shortQuota: '短期额度', longQuota: '长期额度', resetUnknown: '重置时间未知', resetMinutes: '{{count}} 分钟后重置', resetHours: '{{hours}} 小时 {{minutes}} 分钟后重置', resetDays: '{{days}} 天 {{hours}} 小时后重置', afterValidation: '验证后显示', empty: '在线验证后显示 5 小时和周额度', remaining: '{{percent}}% 剩余', title: 'Codex 额度', subtitle: '订阅账号的短期和长期用量窗口' },
    details: { title: '账号详情', conclusion: '检测结论', notValidated: '尚未执行在线验证', credentials: '凭据信息', credential: '凭据', fingerprint: '指纹', refreshToken: 'Refresh Token', exists: '存在', missing: '缺失', plan: '套餐', unknown: '未知', checkedAt: '验证时间', sourceFile: '来源文件', deleteAccount: '删除该账号', apiSupported: '支持官方 API 在线验证', codexSupported: '支持 Codex 上游实际验证', apiHint: '在线检查通过本地原生网络发送，结果不会包含凭据。', codexHint: '发送最小模型请求，根据实际 HTTP 响应判断账号状态。' },
    paste: { eyebrow: '本地解析', title: '粘贴账号 JSON' },
    validation: { eyebrow: '实际请求', title: '在线验证账号', foreignIp: '外国模型建议开启国外 IP / 代理', foreignIpHint: '出口 IP 仅用于提示，不会阻止验证。OpenAI、Codex 等外国模型建议开启代理；国内供应商可按线路情况直接测试。', ipConfirmed: '当前出口适合测试外国模型', checkingIp: '正在检测出口 IP', networkBlocked: '仍可继续，外国模型可能受限', available: '{{count}} 个账号可验证', hint: '账号会按顺序逐个验证，同一时间只发送 1 个请求。OAuth 会读取 Codex 5 小时/周额度。', checkingAccount: '正在串行验证该账号', scope: '验证范围', batch: '本批 25 个', all: '全部待验证账号（串行）' },
    cleanup: { eyebrow: '清理结果', title: '删除凭据失效账号', count: '{{count}} 个账号将被删除', hint: '仅删除在线验证返回 401 的凭据；限流、无权限、网络失败和未验证账号都会保留。' },
    openSource: { eyebrow: '作者与许可证', title: '开源声明', maintainer: '作者与维护者：豫晨', collaboration: '豫晨 × OpenAI Codex 协作开发', dependencies: '核心开源依赖', dependenciesHint: '应用运行、界面与构建直接使用的主要项目', references: '参考与格式兼容项目', referencesHint: '用于研究账号状态与兼容导入格式', codexRef: '官方额度窗口与限流字段映射参考', antigravityRef: '账号状态分类概念参考', converterRef: '账号 JSON 格式兼容参考', sub2apiRef: 'sub2api 导入结构与检测行为参考', footnote: '上述参考项目的源码未打包进 Online testing account。OpenAI Codex 仅协助开发，不随软件分发；本软件不是 OpenAI 官方产品。' },
    guide: { label: '操作指引 · {{current}}/{{total}}', importTitle: '导入账号', importDescription: '选择“导入文件夹”可递归读取整个目录；旁边的“导入文件”支持单个或多个 JSON。大量文件会自动分批处理。', searchTitle: '查找与筛选', searchDescription: '可以搜索邮箱、账号 ID 或格式；下方筛选栏可快速查看待验证、在线正常、凭据失效和需要处理的账号。', validateTitle: '开始在线验证', validateDescription: '点击后会检测出口 IP 并给出网络建议，但不会阻止验证。测试 OpenAI、Codex 等外国模型时仍建议开启国外代理。', resultsTitle: '查看结果与额度', resultsDescription: '列表显示在线状态、Codex 5 小时额度和周额度。点击任意账号，可以在详情页查看完整结论、额度与重置时间。', cleanupTitle: '删除凭据失效账号', cleanupDescription: '检测完成后可删除返回 401 的凭据失效账号。限流、无权限、网络失败和未验证账号不会被误删。', exportTitle: '导出剩余账号', exportDescription: '完成检测和清理后，导出除凭据失效以外的所有账号，生成可再次导入的 sub2api JSON。' },
    notices: { reportExported: '已导出无敏感验证报告', importComplete: '{{source}}完成：{{files}} 个文件，解析 {{accounts}} 个账号', issues: '，{{count}} 个问题', import: '导入', fileImport: '文件导入', folderImport: '文件夹“{{name}}”导入', noJson: '所选文件夹内没有 JSON 文件', folderFailed: '文件夹导入失败：{{message}}', folderFailedGeneric: '文件夹导入失败', jsonOnly: '仅支持 JSON 文件', tooLarge: '文件超过 10 MB', checkingIp: '正在检测当前出口 IP...', ipCheckFailed: '无法检测出口 IP；仍可继续，测试外国模型时建议开启代理', noAccounts: '没有需要验证的账号', validationServiceFailed: '本地验证服务连接失败', tokenRefreshed: '访问令牌已刷新', validationComplete: '在线验证完成：本批次 {{count}} 个凭据', validationCancelled: '验证已取消：完成 {{done}} / {{total}} 个凭据', quotaRefreshed: '额度已刷新', quotaUnavailable: '未获取到额度：{{detail}}', quotaFailed: '额度刷新失败，请检查模型线路或代理连接', exported: '已导出 {{count}} 个剩余账号', deleted: '已删除 {{count}} 个凭据失效账号', notValidated: '未验证', drop: '释放以导入 JSON' },
  } },
  en: { translation: {
    brand: { subtitle: 'Account health and Codex quota checks', version: `v${APP_VERSION.version}` },
    header: { guide: 'Guide', openSource: 'Open source', privacy: 'Credentials stay in this process', desktop: 'Desktop', mobile: 'Mobile', preview: 'Browser preview', switchLanguage: '切换到中文' },
    updates: { check: 'Check updates', available: 'Update available', eyebrow: 'GitHub Releases', title: 'Version {{version}} is available', current: 'You are on the latest version ({{version}})', failed: 'Unable to check for updates. Try again later.', later: 'Later', download: 'Open download page', selectApiKey: 'Import an account or add a custom API provider first', started: 'LAN API service started. Save the pairing token.', stopped: 'LAN API service stopped', startFailed: 'Unable to start LAN API: {{message}}', stopFailed: 'Unable to stop the LAN API service', copied: 'Copied to clipboard', copyFailed: 'Could not copy; please copy it manually', titleLan: 'LAN API service', subtitle: 'Use this phone as an OpenAI-compatible endpoint for paired computers', hint: 'Only /v1/models, /v1/chat/completions, and /v1/responses are forwarded. It runs as a foreground service; stopping it invalidates the pairing token immediately.', proxyHintTitle: 'Proxy and LAN must both work', proxyHint: 'Foreign models usually require a phone proxy. If the computer connects only after the proxy is disabled, that proxy is blocking LAN traffic. Enable Allow LAN / bypass local addresses, or switch to a LAN-compatible proxy. As a temporary workaround, enable the proxy for phone tests and disable it for computer access.', port: 'Service port', start: 'Start API service', stop: 'Stop API service', running: 'Running', idle: 'Stopped', pool: '{{count}} available upstreams', poolReady: 'When a custom provider is active, only that provider is used; disabling it restores the imported account pool', poolManage: 'Tap to manage · {{enabled}} / {{total}} enabled', poolListTitle: 'LAN upstreams', poolActiveCount: '{{enabled}} / {{total}} enabled', providerUpstream: 'Custom API', toggleUpstream: 'Toggle {{name}}', poolUpdated: 'Upstream settings updated and applied to the running service', poolUpdateFailed: 'Could not update upstreams; the previous settings remain active', poolEmptyStopped: 'No upstreams are enabled, so the LAN API service was stopped', poolEmpty: 'Import an account or add a custom API provider', copyAddress: 'Copy API address', copyToken: 'Copy pairing token', tokenUnavailable: 'The service was started outside this app session. Stop and restart it to generate a new pairing token.', test: 'Test connection', retest: 'Test again', testingModels: 'Fetching available models...', testingModel: 'Found {{count}} models; randomly testing {{model}}...', testPassed: 'Test passed · {{elapsed}} ms', testFailed: 'Test failed', testModelDetail: 'Found {{count}} models · Randomly tested {{model}}', testUpstream: 'Upstream: {{name}} · {{protocol}}', testResponse: 'Response: {{response}}', testModels: 'Available models', testNoModels: 'No testable models found', testError: 'Error: {{message}}' },
    splash: { subtitle: 'Account health and Codex quota checks', loading: 'Starting the secure test environment' },
    metrics: { label: 'Account validation metrics', rate: 'Alive rate', verifiedRatio: '{{alive}} / {{tested}} verified', verified: 'Verified', verifiedHint: 'Real requests returned results', pending: 'Pending', invalid: 'Invalid', limited: 'Rate limited', total: 'Total' },
    operations: { label: 'Workspace status', localState: 'Local workspace is saved automatically', attention: '{{count}} accounts need attention', clear: 'No active exceptions', running: 'Validating {{done}} / {{total}}' },
    actions: { importFolder: 'Import folder', importFiles: 'Import files', pasteJson: 'Paste JSON', validate: 'Validate', pauseValidation: 'Pause validation', resumeValidation: 'Resume validation', cancelValidation: 'Cancel validation', cancellingValidation: 'Cancelling', deleteInvalid: 'Delete invalid', exportRemaining: 'Export remaining', exportReport: 'Export validation report', clear: 'Clear', close: 'Close', cancel: 'Cancel', refreshQuota: 'Refresh quota', previous: 'Previous', next: 'Next', finish: 'Finish', exitGuide: 'Exit guide', retryIp: 'Check IP again', startValidation: 'Start validation', confirmDelete: 'Delete', parseImport: 'Parse and import', understood: 'Got it' },
    mobile: { accounts: 'Accounts', details: 'Details', api: 'LAN API' },
    providers: { add: 'Custom API provider', list: 'Custom API providers', eyebrow: 'Upstream configuration', addTitle: 'Add API provider', editTitle: 'Edit API provider', name: 'Name', namePlaceholder: 'For example: Provider 3', protocol: 'Upstream protocol', model: 'Configured model', modelPlaceholder: 'Enter or fetch a model', fetchModels: 'Fetch models', fetchingModels: 'Fetching...', selectModel: 'Select a model', modelsFound: 'Found {{count}} models', noModels: 'No available models returned', modelsHint: 'Fetch supported models from the provider /v1/models endpoint', fetchModelsFirst: 'Enter the Base URL and API key first', fetchModelsFailed: 'Could not fetch models: {{message}}', useInPool: 'Set as the only active API provider', disableActiveFirst: '“{{name}}” is active. Disable it before enabling this provider.', enabled: 'Enabled', disabled: 'Disabled', edit: 'Edit provider', delete: 'Delete provider', save: 'Save provider', saved: 'API provider saved', deleted: 'API provider deleted', invalidUrl: 'Enter a valid HTTP or HTTPS Base URL', required: 'Name, Key, and model are required' },
    search: { placeholder: 'Search email, account ID, or format', clear: 'Clear search' },
    filters: { all: 'All', pending: 'Pending', alive: 'Alive', invalid: 'Invalid', limited: 'Rate limited', attention: 'Needs attention', count: '{{count}} accounts' },
    table: { account: 'Account', source: 'Source', status: 'Status', quota: 'Codex quota', checkedAt: 'Checked', details: 'Details', noResults: 'No matching accounts', pagination: 'Account pagination', pageSummary: 'Showing {{start}}-{{end}} of {{count}}', page: 'Page {{page}} / {{total}}', previousPage: 'Previous page', nextPage: 'Next page' },
    empty: { title: 'Waiting for account data', details: 'Select an account to view details' },
    status: { untested: 'Untested', unsupported: 'Pending', checking: 'Checking', alive: 'Alive', unauthorized: 'Invalid credential', forbidden: 'Forbidden', rate_limited: 'Rate limited', server_error: 'Service error', network_error: 'Network error' },
    formats: { oauth: 'Generic OAuth' },
    quota: { fiveHours: '5 hours', weekly: 'Weekly', days: '{{count}} days', hours: '{{count}} hours', minutes: '{{count}} min', short: 'Short', long: 'Long', shortQuota: 'Short window', longQuota: 'Long window', resetUnknown: 'Reset time unknown', resetMinutes: 'Resets in {{count}} min', resetHours: 'Resets in {{hours}}h {{minutes}}m', resetDays: 'Resets in {{days}}d {{hours}}h', afterValidation: 'Shown after validation', empty: 'Validate online to show 5-hour and weekly quota', remaining: '{{percent}}% remaining', title: 'Codex quota', subtitle: 'Short and long subscription usage windows' },
    details: { title: 'Account details', conclusion: 'Result', notValidated: 'Online validation has not run', credentials: 'Credential details', credential: 'Credential', fingerprint: 'Fingerprint', refreshToken: 'Refresh Token', exists: 'Present', missing: 'Missing', plan: 'Plan', unknown: 'Unknown', checkedAt: 'Checked', sourceFile: 'Source file', deleteAccount: 'Delete account', apiSupported: 'Official API validation supported', codexSupported: 'Real Codex upstream validation supported', apiHint: 'The native network layer sends the check and never returns credentials.', codexHint: 'Sends a minimal model request and classifies the real HTTP response.' },
    paste: { eyebrow: 'Local parser', title: 'Paste account JSON' },
    validation: { eyebrow: 'Real request', title: 'Validate accounts', foreignIp: 'A foreign IP / proxy is recommended for foreign models', foreignIpHint: 'The exit-IP check is advisory and never blocks validation. Use a proxy for OpenAI, Codex, and other foreign models; domestic providers may be tested according to their route.', ipConfirmed: 'Exit is suitable for foreign models', checkingIp: 'Checking exit IP', networkBlocked: 'You can continue; foreign models may be unavailable', available: '{{count}} accounts can be validated', hint: 'Accounts are validated sequentially with only one request in flight. OAuth also reads the Codex 5-hour and weekly quota.', checkingAccount: 'Sequentially validating this account', scope: 'Validation scope', batch: 'Next 25', all: 'All pending accounts (sequential)' },
    cleanup: { eyebrow: 'Cleanup', title: 'Delete invalid credentials', count: '{{count}} accounts will be deleted', hint: 'Only credentials that returned HTTP 401 are deleted. Rate limits, forbidden, network failures, and untested accounts are kept.' },
    openSource: { eyebrow: 'Author and licenses', title: 'Open-source notice', maintainer: 'Author and maintainer: 豫晨', collaboration: '豫晨 × OpenAI Codex collaboration', dependencies: 'Core open-source dependencies', dependenciesHint: 'Primary runtime, UI, and build projects', references: 'Referenced and compatible projects', referencesHint: 'Used for account-state research and import compatibility', codexRef: 'Official quota-window and rate-limit field reference', antigravityRef: 'Account-state classification reference', converterRef: 'Account JSON compatibility reference', sub2apiRef: 'sub2api schema and probe behavior reference', footnote: 'Referenced source code is not bundled with Online testing account. OpenAI Codex assisted development and is not distributed with the app. This is not an official OpenAI product.' },
    guide: { label: 'Guide · {{current}}/{{total}}', importTitle: 'Import accounts', importDescription: 'Import a folder recursively on desktop, or choose one or more JSON files. Large imports are processed in batches.', searchTitle: 'Search and filter', searchDescription: 'Search by email, account ID, or format. Filters show pending, alive, invalid, and attention states.', validateTitle: 'Validate online', validateDescription: 'The app checks the exit IP and shows network advice without blocking validation. A foreign proxy is still recommended for OpenAI, Codex, and other foreign models.', resultsTitle: 'Review results and quota', resultsDescription: 'The list shows account state plus Codex 5-hour and weekly quota. Select an account for the complete result and reset time.', cleanupTitle: 'Delete invalid credentials', cleanupDescription: 'Remove only credentials that returned HTTP 401. Other failure classes remain untouched.', exportTitle: 'Export remaining accounts', exportDescription: 'Export every account except invalid credentials as re-importable sub2api JSON.' },
    notices: { reportExported: 'Exported redacted validation report', importComplete: '{{source}} complete: {{files}} files, {{accounts}} accounts parsed', issues: ', {{count}} issues', import: 'Import', fileImport: 'File import', folderImport: 'Folder “{{name}}” import', noJson: 'No JSON files found in the selected folder', folderFailed: 'Folder import failed: {{message}}', folderFailedGeneric: 'Folder import failed', jsonOnly: 'Only JSON files are supported', tooLarge: 'File exceeds 10 MB', checkingIp: 'Checking the current exit IP...', ipCheckFailed: 'Unable to detect the exit IP; you can continue, but use a proxy for foreign models', noAccounts: 'No accounts need validation', validationServiceFailed: 'Local validation service is unavailable', tokenRefreshed: 'Access token refreshed', validationComplete: 'Validation complete: {{count}} credentials', validationCancelled: 'Validation cancelled: {{done}} / {{total}} credentials completed', quotaRefreshed: 'Quota refreshed', quotaUnavailable: 'Quota unavailable: {{detail}}', quotaFailed: 'Quota refresh failed; check the provider route or proxy', exported: 'Exported {{count}} remaining accounts', deleted: 'Deleted {{count}} invalid accounts', notValidated: 'Untested', drop: 'Drop to import JSON' },
  } },
} as const;

const savedLanguage = localStorage.getItem('ota-language');
const initialLanguage = savedLanguage === 'en' || savedLanguage === 'zh'
  ? savedLanguage
  : navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en';

void i18n.use(initReactI18next).init({
  resources,
  lng: initialLanguage,
  fallbackLng: 'zh',
  supportedLngs: ['zh', 'en'],
  interpolation: { escapeValue: false },
});

i18n.on('languageChanged', (language) => {
  localStorage.setItem('ota-language', language);
  document.documentElement.lang = language === 'en' ? 'en' : 'zh-CN';
});

export default i18n;
